apiVersion: batch/v1
kind: Job
metadata:
  name: plm-infrastructure-migrate
spec:
  template:
    spec:
      containers:
        - name: plm-infrastructure
          image: ghcr.io/altair288/plm-infrastructure:sha-b3d35cc232c5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/altair288/plm-auth-service:sha-b3d35cc232c5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: attribute-service
spec:
  template:
    spec:
      containers:
        - name: attribute-service
          image: ghcr.io/altair288/plm-attribute-service:sha-b3d35cc232c5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  template:
    spec:
      containers:
        - name: gateway
          image: ghcr.io/altair288/plm-gateway:sha-b3d35cc232c5