apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/altair288/plm-cloud-frontend:sha-cbd9c67d42ba